# Generated from tools.yaml by scripts/tools.mjs. Do not edit by hand.
cask "google-chrome"
cask "github"
cask "ghostty"
cask "sublime-text"
cask "zed"
cask "postman"
cask "docker"
brew "gh"
brew "kubectl"
brew "helm"
brew "vault"
brew "kustomize"
brew "himalaya"
brew "ntfy"
